[manifest]
version = "2.1"
priority = 0

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "langOption.languages = *"
position = "after"
payload = "table.insert(langOption.languages, 'zh_cn')"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "--self.optionsMenu:addOption('optionsLanguage','language',optionsHeight*1)"
position = "at"
payload = "self.optionsMenu:addOption('optionsLanguage','language',optionsHeight*1)"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "self.optionsMenu:addOption('optionsAccessibility','accessibility',optionsHeight*1)"
position = "at"
payload = "self.optionsMenu:addOption('optionsAccessibility','accessibility',optionsHeight*2)"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "self.optionsMenu:addOption('optionsGraphics','graphics',optionsHeight*2)"
position = "at"
payload = "self.optionsMenu:addOption('optionsGraphics','graphics',optionsHeight*3)"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "self.optionsMenu:addOption('optionsAudio','audio',optionsHeight*3)"
position = "at"
payload = "self.optionsMenu:addOption('optionsAudio','audio',optionsHeight*4)"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "self.optionsMenu:addOption('optionsGameplay','gameplay',optionsHeight*4)"
position = "at"
payload = "self.optionsMenu:addOption('optionsGameplay','gameplay',optionsHeight*5)"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "self.optionsMenu:addOption('optionsKeybinds', 'keybinds', optionsHeight*5)"
position = "at"
payload = "self.optionsMenu:addOption('optionsKeybinds', 'keybinds', optionsHeight*6)"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = '''
		self.optionsMenu:addOption('optionsJokes',function()
			self.jokesData = helpers.copytable(savedata.aprilFools,2)
			self.optionsMenu:setSubmenu('jokes')
		end,optionsHeight*6)
'''
position = "at"
payload = '''
		self.optionsMenu:addOption('optionsJokes',function()
			self.jokesData = helpers.copytable(savedata.aprilFools,2)
			self.optionsMenu:setSubmenu('jokes')
		end,optionsHeight*7)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = 'loc.load("data/localization.json")'
position = "after"
payload = '''
-- 加载自定义中文翻译
print("=== Loading Chinese Localization ===")
local newLanguage = 'zh_cn'
if love.filesystem.exists('Mods/ChsMod') then
	local chsLocJson = dpf.loadJson("Mods/ChsMod/localization.json", {})

	if chsLocJson then
		local count = 0
		for k, v in pairs(loc.json) do
			if chsLocJson[k] and chsLocJson[k][newLanguage] then
				loc.json[k][newLanguage] = chsLocJson[k][newLanguage]
				count = count + 1
			else
				loc.json[k][newLanguage] = loc.json[k]['en']
			end
		end
		loc.json['lang_' .. newLanguage] = {}
		for k, v in pairs(loc.json.optionsLanguage) do
			loc.json['lang_' .. newLanguage][k] = chsLocJson['lang_' .. newLanguage][newLanguage]
		end
		print(newLanguage .. " localization merged! Keys: " .. count)
	else
		print("Failed to decode Json: ".. locPath)
	end
else
	print("ERROR: 'Mods/ChsMod' folder not exists!")
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "preload/fonts.lua"
pattern = 'fonts.censorblock:setFallbacks(fonts.terminal)'
position = "after"
payload = '''
-- 加载中文字体
print("=== Loading Chinese Font ===")
if love.filesystem.exists('Mods/ChsMod') then
	local chineseFontList = {
		fusionPixel8 = {fontFileName = "fusion-pixel-8px-proportional-zh_hans.ttf", fontSize = 8},
		fusionPixel12 = {fontFileName = "fusion-pixel-12px-proportional-zh_hans.ttf", fontSize = 12},
		changBanDianSong = {fontFileName = "ChangBanDianSong-16-SC.ttf", fontSize = 16},
		unifont = {fontFileName = "unifont-17.0.04.otf", fontSize = 16},
	}
	for fontName, fontInfo in pairs(chineseFontList) do
		local pathToFontFile = "Mods/ChsMod/fonts/" .. fontInfo.fontFileName
		if love.filesystem.exists(pathToFontFile) then
			print("Loading font: " .. fontInfo.fontFileName)

			local loadSuccess, loadedFont = pcall(love.graphics.newFont, pathToFontFile, fontInfo.fontSize)
			if loadSuccess then
				fonts[fontName] = loadedFont
				print("Loaded successfully: " .. fontInfo.fontFileName)
			else
				print("ERROR: Failed to load font: " .. tostring(loadedFont))
			end
		else
			print("ERROR: Font file not exists: " .. pathToFontFile)
		end
	end

	fonts['fusionPixel12Glitched'] = love.graphics.newImageFont('Mods/ChsMod/fonts/fp12Garbage.png', '介地弹反侧挑额联返连！击回动外战击向跳雷绍', 1)
	fonts['fusionPixel8Glitched'] = love.graphics.newImageFont('Mods/ChsMod/fonts/fp8Garbage.png', '精准度', 1)
else
	print("ERROR: 'Mods/ChsMod' folder not exists!")
end
if fonts.changBanDianSong then fonts.changBanDianSong:setLineHeight(1.1) end
fonts.digitalDiscoGlitched:setFallbacks(fonts.fusionPixel12Glitched)
fonts.mainGlitched:setFallbacks(fonts.fusionPixel8Glitched)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '--Demo save update code'
position = "before"
payload = '''
if savedata.options.language == 'zh_cn' then
	if fonts.fusionPixel8 then
		fonts.fusionPixel8:setLineHeight(0.75)
		fonts.main = fonts.fusionPixel8
	end
	if fonts.fusionPixel12 then
		fonts.fusionPixel12:setLineHeight(0.75)
		fonts.digitalDisco = fonts.fusionPixel12
		fonts.jfdot = fonts.fusionPixel12
	end
	if fonts.unifont then
		fonts.jfdot2 = fonts.unifont
	end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = "love.graphics.setFont(fonts.ancient)"
position = "at"
payload = '''
if fonts.changBanDianSong and savedata.options.language == 'zh_cn' then
	love.graphics.setFont(fonts.changBanDianSong)
else
	love.graphics.setFont(fonts.ancient)
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "lib/rtf.lua"
pattern = "local rtf = {"
position = "before"
payload = '''
local unbreakCharacterMap =
	"!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\\[]^_`" ..
	"abcdefghijklmnopqrstuvwxyz{}~¡¢£¤¥¦§¨©ª«¬？®¯°±²³´µ¶·¸¹º»¼½¾¿" ..
	"ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿΩ" ..
	"（“【《"

local unbreakSymbolMap = "。，！？、…—）”】》"

'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "lib/rtf.lua"
pattern = "function rtf:update(dt)"
position = "before"
payload = '''
function rtf:isUnbreakChar(char)
	if not char or char == '' then return false end
	if string.find(unbreakCharacterMap, char, 1, true) then return true end
	return false
end

function rtf:followingUnbreakSym(text, startPos, chrOffset)
	chrOffset = chrOffset + 1
	local chr = rtf.sub(text, startPos + chrOffset, startPos + chrOffset)
	if startPos + chrOffset <= utf8.len(text) and chr then
		if string.find(unbreakSymbolMap, chr, 1, true) then return true end
	end
	return false
end

'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "lib/rtf.lua"
pattern = "word = word .. chr"
position = "after"
payload = "if not(self:isUnbreakChar(chr)) and not(self:followingUnbreakSym(text, startPos, chrOffset)) then brk = true end"
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "lib/rtf.lua"
pattern = "elseif l == ' ' and wrapLen > 0 then*"
position = "at"
payload = "elseif not(self:isUnbreakChar(l)) and wrapLen > 0 then"
match_indent = true
times = 3

[[patches]]
[patches.pattern]
target = "lib/rtf.lua"
pattern = "if l == ' ' and wrapLen > 0 then"
position = "at"
payload = "if not(self:isUnbreakChar(l)) and wrapLen > 0 then"
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "for i = 1, #combo_print do"
position = "at"
payload = "for i = 1, utf8.len(combo_print) do"
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "if i == 1 then combo_print = ' ' .. string.sub(combo_print, 2, -1) end"
position = "at"
payload = '''
local bpos = utf8.offset(combo_print, i)
local epos = utf8.offset(combo_print, i + 1) or (#combo_print + 1)
if i == 1 then
	combo_print = ' ' .. string.sub(combo_print, epos, -1)
else
'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "combo_print = string.sub(combo_print, 1, i) .. ' ' .. string.sub(combo_print, i+2, -1)"
position = "at"
payload = "combo_print = string.sub(combo_print, 1, bpos - 1) .. ' ' .. string.sub(combo_print, epos, -1) end"
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "for i = 1, #text_print do"
position = "at"
payload = "for i = 1, utf8.len(text_print) do"
times = 2
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "if i == 1 then text_print = ' ' .. string.sub(text_print, 2, -1) end"
position = "at"
payload = '''
local bpos = utf8.offset(text_print, i)
local epos = utf8.offset(text_print, i + 1) or (#text_print + 1)
if i == 1 then
	text_print = ' ' .. string.sub(text_print, epos, -1)
else
'''
times = 2
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "text_print = string.sub(text_print, 1, i) .. ' ' .. string.sub(text_print, i+2, -1)"
position = "at"
payload = "text_print = string.sub(text_print, 1, bpos - 1) .. ' ' .. string.sub(text_print, epos, -1) end"
times = 2
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "for i = 1, #accStr do"
position = "at"
payload = "for i = 1, utf8.len(accStr) do"
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "if i == 1 then accStr = ' ' .. string.sub(accStr, 2, -1) end"
position = "at"
payload = '''
local bpos = utf8.offset(accStr, i)
local epos = utf8.offset(accStr, i + 1) or (#accStr + 1)
if i == 1 then
	accStr = ' ' .. string.sub(accStr, epos, -1)
else
'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "accStr = string.sub(accStr, 1, i) .. ' ' .. string.sub(accStr, i+2, -1)"
position = "at"
payload = "accStr = string.sub(accStr, 1, bpos - 1) .. ' ' .. string.sub(accStr, epos, -1) end"
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "for i = 1, #str do"
position = "at"
payload = "for i = 1, utf8.len(str) do"
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "if i == 1 then str = ' ' .. string.sub(str, 2, -1) end"
position = "at"
payload = '''
local bpos = utf8.offset(str, i)
local epos = utf8.offset(str, i + 1) or (#str + 1)
if i == 1 then
	str = ' ' .. string.sub(str, epos, -1)
else
'''
times = 1
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "str = string.sub(str, 1, i) .. ' ' .. string.sub(str, i+2, -1)"
position = "at"
payload = "str = string.sub(str, 1, bpos - 1) .. ' ' .. string.sub(str, epos, -1) end"
times = 1
match_indent = true
